server:
  port: 8761

eureka:
  eurekaServer:
    port: 80
    domainName: eureka.example.com
    context: eureka/v2
  datacenter: cloud
  shouldUseDns: true
  region: us-east-1

spring:
  application:
    name: eureka-server

